products/urls.py
from django.urls import path

from products.views import (CartDetailView, CatalogView, CompareView,
                            ProductDetailsView, SaleView, add_to_comparison,
                            cart_add_product, cart_add_product_position,
                            cart_remove)

app_name = "products"
urlpatterns = [
    path("catalog/", CatalogView.as_view(), name="catalog"),
    path("catalog//<int:page>", CatalogView.listing, name="catalog-by-page"),
    path("product/<int:pk>/", ProductDetailsView.as_view(), name="product"),
    path("compare/", CompareView.as_view(), name="compare"),
    path("add_to_comparison/<int:pk>/", add_to_comparison, name="add_to_comparison"),
    path("sale/", SaleView.as_view(), name="sale"),
    path("cart/", CartDetailView.as_view(), name="cart_detail"),
    path(
        "cart/add/product/<int:product_id>/", cart_add_product, name="cart_add_product"
    ),
    path(
        "cart/add/product_position/<int:product_position_id>/",
        cart_add_product_position,
        name="cart_add_product_position",
    ),
    path("cart/remove/<int:product_position_id>/", cart_remove, name="cart_remove"),
]

store/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from products.views import IndexView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("allauth.urls")),
    path("", IndexView.as_view(), name="index"),
    path("products/", include("products.urls")),
    path("orders/", include("orders.urls")),
    path("users/", include("users.urls")),
    path("__debug__/", include("debug_toolbar.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/forms.py
from django import forms
from django.forms import ModelForm, Textarea

from products.models import Review


class ReviewCreationForm(ModelForm):
    class Meta:
        model = Review
        fields = ("body",)
        widgets = {
            "body": Textarea(attrs={"placeholder": "Отзыв", "class": "form-textarea"}),
        }


class ProductFilterForm(forms.Form):
    min_price = forms.DecimalField(required=False)
    max_price = forms.DecimalField(required=False)

    in_stock = forms.BooleanField(
        required=False,
        label="Только товары в наличии",
        widget=forms.CheckboxInput(attrs={})
    )

    free_shipping = forms.BooleanField(
        required=False,
        label="С бесплатной доставкой",
        widget=forms.CheckboxInput(attrs={})
    )

    product_name = forms.CharField(
        max_length=100,
        required=False,
        label="",
        widget=forms.TextInput(attrs={"class": "form-input form-input_full", "placeholder": "Название"})
    )


class AddProductToCartForm(forms.Form):
    """
    Form to add products to the cart or override quantity of product_position already  in the cart.
    """

    quantity = forms.IntegerField()
    is_override = forms.BooleanField(
        required=False, initial=False, widget=forms.HiddenInput
    )

products/views.py
from datetime import datetime

from django.core.paginator import Paginator
from django.db.models import Avg, Count, Max, Min, Q, Sum
from django.http import HttpRequest, HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse_lazy
from django.views.decorators.http import require_POST
from django.views.generic import DetailView, ListView, TemplateView
from django.views.generic.base import ContextMixin

from products.cart import Cart
from products.forms import (AddProductToCartForm, ProductFilterForm,
                            ReviewCreationForm)
from products.models import (AdBanner, Category, Offer, Product,
                             ProductPosition, Review)
from users.models import Action
from users.utils import create_action


class BaseMixin(ContextMixin):
    """Put data necessary for base.html template into context."""

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["categories"] = (
            Category.objects.filter(parent=None, is_deleted=False)
            .order_by("pk")
            .prefetch_related("subcategories")
        )
        return context


class IndexView(BaseMixin, TemplateView):
    template_name = "index.html"

    def get_context_data(self, **kwargs):
        """Put current "Limited offer" chosen product and Ad banner into context."""
        context = super().get_context_data(**kwargs)
        context_data = {
            "chosen_product": Product.objects.filter(is_chosen=True).first(),
            "featured_categories": Category.get_featured_categories(),
            "popular_products": Product.get_popular_products(),
            "limited_edition_products": Product.get_limited_edition_products(),
            "banners": AdBanner.get_banners(),
            "categories": Category.objects.filter(parent=None, is_deleted=False)
            .order_by("pk")
            .prefetch_related("subcategories")
        }
        context.update(context_data)
        return context_data


class CatalogView(BaseMixin, ListView):
    paginate_by = 6
    model = Product
    template_name = "products/catalog.html"
    queryset = (
        Product.objects.filter(is_deleted=False)
        .select_related("category")
        .prefetch_related("tags", "images")
    )
    context_object_name = "products"

    def get_queryset(self):
        queryset = (
            Product.objects.filter(is_deleted=False)
            .select_related("category")
            .prefetch_related("tags", "images")
        )

        form = ProductFilterForm(self.request.GET)

        if form.is_valid():
            product_name = form.cleaned_data.get("product_name")
            in_stock = form.cleaned_data.get("in_stock")
            free_shipping = form.cleaned_data.get("free_shipping")
            price_range = self.request.GET.get("price")
            sort_param = self.request.GET.get("sort_param")
            tag_chosen = self.request.GET.get("tags")

            if product_name:
                queryset = queryset.filter(
                    Q(title__icontains=product_name)
                    | Q(title__icontains=product_name.capitalize())
                    | Q(title__icontains=product_name.lower())
                )

            query = self.request.GET.get("query")
            if query:
                queryset = queryset.filter(
                    Q(title__icontains=query)
                    | Q(title__icontains=query.capitalize())
                    | Q(title__icontains=query.lower())
                )
            category = self.request.GET.get("category")
            if category:
                queryset = queryset.filter(category=category)

            if in_stock:
                queryset = queryset.annotate(total_quantity=Sum("productposition__quantity"))
                queryset = queryset.filter(total_quantity__gt=0)

            if free_shipping:
                queryset = queryset.filter(productposition__free_shipping=True)

            if price_range or sort_param == "price_l2h" or sort_param == "price_h2l":
                queryset = queryset.annotate(price=Avg("productposition__price"))

            if price_range:
                min_price, max_price = map(int, price_range.split(";"))
                queryset = queryset.filter(price__gte=min_price, price__lte=max_price)

            if sort_param == "price_l2h":
                queryset = queryset.order_by("price")

            elif sort_param == "price_h2l":
                queryset = queryset.order_by("-price")

            if sort_param == "pop_l2h":
                queryset = queryset.annotate(count_orders=Count("productposition__orderitem__order"))
                queryset = queryset.order_by("count_orders")
            elif sort_param == "pop_h2l":
                queryset = queryset.annotate(count_orders=Count("productposition__orderitem__order"))
                queryset = queryset.order_by("-count_orders")

            if sort_param == "review_l2h":
                queryset = queryset.annotate(count_reviews=Count("reviews"))
                queryset = queryset.order_by("count_reviews")
            elif sort_param == "review_h2l":
                queryset = queryset.annotate(count_reviews=Count("reviews"))
                queryset = queryset.order_by("-count_reviews")

            if sort_param == "new_l2h":
                queryset = queryset.order_by("updated")
            elif sort_param == "new_h2l":
                queryset = queryset.order_by("-updated")

            if tag_chosen and tag_chosen != 'None':
                queryset = queryset.filter(tags=tag_chosen)

        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        def get_payload(names_param):
            payload = ""
            for k, list_ in self.request.GET.lists():
                if k in names_param:
                    continue
                for v in list_:
                    payload += "&" + k + "=" + v
            return payload

        price_range = self.request.GET.get("price")
        min_price_of_all = ProductPosition.objects.values("price").aggregate(Min("price"))["price__min"]
        max_price_of_all = ProductPosition.objects.values("price").aggregate(Max("price"))["price__max"]
        sort_param = self.request.GET.get("sort_param")
        tags_param = self.request.GET.get("tags")
        if price_range:
            min_price, max_price = map(int, price_range.split(";"))
        else:
            min_price = min_price_of_all
            max_price = max_price_of_all
        context["min_price"] = min_price
        context["max_price"] = max_price
        context["min_price_of_all"] = min_price_of_all
        context["max_price_of_all"] = max_price_of_all
        context["sort_param"] = sort_param
        context["tags_param"] = tags_param
        context["filter_form"] = ProductFilterForm(self.request.GET)
        context["payload"] = get_payload(["page"])
        context["sort_payload"] = get_payload(["page", "sort_param"])
        context["tags_payload"] = get_payload(["page", "tags"])

        return context

    def listing(self):
        catalog = Product.objects.all()
        paginator = Paginator(catalog, 6)
        page_number = self.GET.get("page")
        page_obj = paginator.get_page(page_number)
        return render(self, "products/catalog.html", {"page_obj": page_obj})


class ProductDetailsView(BaseMixin, DetailView):
    template_name = "products/product.html"
    queryset = (
        Product.objects.filter(is_deleted=False)
        .select_related("category")
        .prefetch_related("tags", "images")
    )
    context_object_name = "product"

    def get_success_url(self):
        return reverse_lazy("products:product", args=(self.kwargs["pk"],))

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["form"] = ReviewCreationForm()
        context["reviews"] = Review.objects.filter(product=self.object)
        context[
            "product_positions"
        ] = self.object.productposition_set.all().prefetch_related("seller")
        return context

    def get(self, request, *args, **kwargs):
        """
        Create Action instance for authenticated user to track product viewing history.
        """

        if self.request.user.is_authenticated:
            create_action(
                user=self.request.user,
                verb=Action.VIEW_PRODUCT,
                target=self.get_object(),
            )

        return super().get(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            return redirect("account_login")
        self.object = self.get_object()
        form = ReviewCreationForm(request.POST)
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def form_valid(self, form):
        form.instance.author = self.request.user
        form.instance.product = self.object
        form.save()
        return HttpResponseRedirect(self.get_success_url())

    def form_invalid(self, form):
        return self.render_to_response(self.get_context_data(form=form))


def add_to_comparison(request, pk):
    comparison_products = request.session.get("comparison_products", [])
    if len(comparison_products) >= 4:
        del request.session["comparison_products"]
        comparison_products = []
    if pk in comparison_products:
        comparison_products.remove(pk)
        request.session["comparison_products"] = comparison_products
    else:
        comparison_products.append(pk)
        request.session["comparison_products"] = comparison_products

    referer = request.META.get("HTTP_REFERER", None)
    if referer:
        return HttpResponseRedirect(referer)
    else:
        return redirect("products:catalog")

templates/products/compare.html
{% extends "base.html" %}
{% load static %}

{% block content %}
    <div class="Middle">
        <div class="wrap" style="padding-left: 0; margin-left: 0;">
            <div class="Product" style="padding-left: 0; margin-left: 0;">
                {% if error_message %}
                    <p>{{ error_message }}</p>
                {% else %}
                    {% if impossible_to_compare %}
                        <p style="padding-left: 45px;">{{ impossible_to_compare }}</p>

                    {% else %}
                        <form method="get" action="{% url 'products:compare' %}"
                              style="padding-left: 45px;">
                            <input type="hidden" name="show_differences" value="false">
                            <label>
                                <input type="checkbox" name="show_differences" value="true"
                                       {% if show_differences %}checked{% endif %}/>
                                Только различающиеся характеристики
                            </label>
                            <input type="submit" value="Применить фильтр"
                                   style="width: 150px; height: 30px;">
                        </form>
                    {% endif %}
                    <div class="ProductCard">
                    {% for product in products %}
                        <div class="ProductCard-desc">
                            <div class="ProductCard-header">
                                <h2 class="ProductCard-title">{{ product.title }}
                                </h2>
                                <div class="ProductCard-look">
                                    {% with product.images.all|first as img %}
                                        {% if img %}
                                            <div class="ProductCard-photo">
                                                <img src="{{ img.image_url }}" alt="{{ img.image.name }}">
                                            </div>
                                        {% endif %}
                                    {% endwith %}
                                </div>
                                <div class="Tabs Tabs_default">
                                    {% if not impossible_to_compare %}
                                        <div class="Tabs-wrap">
                                            <div class="Tabs-block" id="description">
                                                <div class="table">
                                                    <table>
                                                        <tr>
                                                            <th class="hed">Характеристика</th>
                                                            <th class="hed">Значение</th>
                                                        </tr>
                                                        {% if not show_differences %}
                                                            <tr>
                                                                {% if all_categories_equal %}
                                                                    <td class="comparis">Тип</td>
                                                                    <td class="comparis">{{ product.category }}</td>
                                                                {% else %}
                                                                    <td>Тип</td>
                                                                    <td>{{ product.category }}</td>
                                                                {% endif %}
                                                            </tr>
                                                        {% endif %}
                                                        {% if product.features %}
                                                            {% for key, value in product.features.items %}
                                                                {% if not show_differences or key not in highlighted_keys %}
                                                                    <tr>
                                                                        {% if key in highlighted_keys %}
                                                                            <td class="comparis">{{ key }}</td>
                                                                            <td class="comparis"> {{ value }}</td>
                                                                        {% else %}
                                                                            <td>{{ key }}</td>
                                                                            <td> {{ value }}</td>
                                                                        {% endif %}
                                                                    </tr>
                                                                {% endif %}
                                                            {% endfor %}
                                                        {% endif %}
                                                    </table>
                                                </div>
                                            </div>
                                        </div>
                                    {% endif %}
                                    <a class="Card-btn"
                                       href="{% url 'products:add_to_comparison' pk=product.pk %}">
                                        <img src="{% static 'assets/img/icons/exchange.svg' %}"
                                             alt="exchange.svg"/>
                                    </a>
                                </div>
                            </div>
                            <div class="ProductCard-info">
                                <div class="ProductCard-cost">
                                    <div class="ProductCard-price">
                                        ${{ product.get_avg_price_with_discount }}
                                    </div>
                                </div>
                            </div>
                            <form action="{% url 'products:cart_add_product' product.id %}" method="post">
                                <div class="ProductCard-cart">
                                    {% csrf_token %}
                                    <input type="hidden" name="quantity" value="1" required>
                                    <input type="hidden" name="is_override" id="id_is_override">
                                    <div class="ProductCard-cartElement">
                                        <button class="btn btn_primary" type="submit">
                                            <img class="btn-icon" src="{% static 'assets/img/icons/card/cart_white.svg' %}" alt="cart_white.svg"/>
                                            <span class="btn-content">Добавить в корзину</span>
                                        </button>
                                    </div>
                                </div>
                            </form>
                        </div>
                    {% endfor %}
                {% endif %}
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/products/product_image_preview.html
{# Used to render `ProductImage.image` preview in `ProductImageInline`. #}
<img src="{{ product_image.image_url }}" style="max-width: 150px;">

templates/products/sale.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<div class="Middle">
    <div class="wrap">
        <div class="Article">
            <ul>
                {% if offers %}
                    {% for offer in offers %}
                        <li>
                            <h3 class="modal-title">{{ offer.description }}</h3>
                            <p>С {{ offer.date_start|date:"d.m.Y" }} по {{ offer.date_end|date:"d.m.Y" }}</p>
                        </li>
                    {% endfor %}
                {% else %}
                    <h3 class="modal-title">Скидок пока нет.</h3>
                {% endif %}
            </ul>
        </div>
    </div>
</div>
{% endblock %}