products/urls.py
from django.urls import path

from products.views import (CartDetailView, CatalogView, CompareView,
                            ProductDetailsView, SaleView, add_to_comparison,
                            cart_add_product, cart_add_product_position,
                            cart_remove)

app_name = "products"
urlpatterns = [
    path("catalog/", CatalogView.as_view(), name="catalog"),
    path("catalog//<int:page>", CatalogView.listing, name="catalog-by-page"),
    path("product/<int:pk>/", ProductDetailsView.as_view(), name="product"),
    path("compare/", CompareView.as_view(), name="compare"),
    path("add_to_comparison/<int:pk>/", add_to_comparison, name="add_to_comparison"),
    path("sale/", SaleView.as_view(), name="sale"),
    path("cart/", CartDetailView.as_view(), name="cart_detail"),
    path(
        "cart/add/product/<int:product_id>/", cart_add_product, name="cart_add_product"
    ),
    path(
        "cart/add/product_position/<int:product_position_id>/",
        cart_add_product_position,
        name="cart_add_product_position",
    ),
    path("cart/remove/<int:product_position_id>/", cart_remove, name="cart_remove"),
]

store/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from products.views import IndexView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("allauth.urls")),
    path("", IndexView.as_view(), name="index"),
    path("products/", include("products.urls")),
    path("orders/", include("orders.urls")),
    path("users/", include("users.urls")),
    path("__debug__/", include("debug_toolbar.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path

from users.views import (AccountDetailView, ActionListView, EmailSentView,
                         EmailView, HistoryOrderView, PasswordView,
                         UserUpdateView)

app_name = "users"

urlpatterns = [
    path("account/", AccountDetailView.as_view(), name="account"),
    path("e-mail/", EmailView.as_view(), name="e-mail"),
    path("e-mail/sent/", EmailSentView.as_view(), name="email_sent"),
    path("password/", PasswordView.as_view(), name="password"),
    path("history-order/<int:pk>/", HistoryOrderView.as_view(), name="history_order"),
    path("profile/<int:pk>/", UserUpdateView.as_view(), name="profile"),
    path("viewhistory/", ActionListView.as_view(), name="viewhistory"),
]

templates/base.html
{% load static %}

<!DOCTYPE html>
<!--[if IE 7]>
<html class="ie7" lang="ru">
<![endif]-->
<!--[if IE 8]>
<html class="ie8" lang="ru">
<![endif]-->
<!--[if IE 9]>
<html class="ie9" lang="ru">
<![endif]-->
<!--[if IE 10]>
<html class="ie10" lang="ru">
<![endif]-->
<!--[if IE 11]>
<html class="ie11" lang="ru">
<![endif]-->
<!--[if gt IE 11]><!-->
<html lang="ru">
<!--<![endif]-->

  <head>
    <title>Megano</title>
    <meta name="description" content="Описание страницы">
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=0">
    <link href="{% static 'favicon.ico' %}" rel="shortcut icon">
    <link rel="preload" href="{% static 'assets/fonts/Roboto/Roboto-Regular.woff' %}" as="font">
    <link rel="preload" href="{% static 'assets/fonts/Roboto/Roboto-Italic.woff' %}" as="font">
    <link rel="preload" href="{% static 'assets/fonts/Roboto/Roboto-Bold.woff' %}" as="font">
    <link rel="preload" href="{% static 'assets/fonts/Roboto/Roboto-Bold_Italic.woff' %}" as="font">
    <link rel="preload" href="{% static 'assets/fonts/Roboto/Roboto-Light.woff' %}" as="font">
    <link rel="preload" href="{% static 'assets/fonts/Roboto/Roboto-Light_Italic.woff' %}" as="font">
    <link rel="stylesheet" href="{% static 'assets/css/fonts.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/basic.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/extra.css' %}">
    <script src="{% static 'assets/plg/CountDown/countdown.js' %}"></script>
    <!--[if lt IE 9]>
    <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script><![endif]-->
  </head>

  <body class="Site">
{% block header %}
    <header class="Header">
      <div class="ControlPanel">
        <div class="wrap">
          <div class="row ControlPanel-row">
            <div class="row-block">
              <div class="row ControlPanel-rowSplit">
                <div class="row-block hide_700">
                  <ul class="menu menu_img menu_smallImg ControlPanel-menu">
                    <li class="menu-item">
                      <a class="menu-link" href="#">
                        <img src="{% static 'assets/img/icons/socialHeader/tw.svg' %}" alt="tw.svg"/>
                      </a>
                    </li>
                    <li class="menu-item">
                      <a class="menu-link" href="#">
                        <img src="{% static 'assets/img/icons/socialHeader/in.svg' %}" alt="in.svg"/>
                      </a>
                    </li>
                    <li class="menu-item">
                      <a class="menu-link" href="#">
                        <img src="{% static 'assets/img/icons/socialHeader/pt.svg' %}" alt="pt.svg"/>
                      </a>
                    </li>
                    <li class="menu-item">
                      <a class="menu-link" href="#">
                        <img src="{% static 'assets/img/icons/socialHeader/mail.svg' %}" alt="mail.svg"/>
                      </a>
                    </li>
                  </ul>
                </div>
              </div>
            </div>
            <nav class="row-block">
              <div class="row ControlPanel-rowSplit">
                <div class="row-block">

                  {% if not user.is_authenticated %}
                    <a class="ControlPanel-title" href="{% url 'account_login' %}">
                      Вход
                    </a>
                    <a class="ControlPanel-title" href="{% url 'account_signup' %}">
                      Регистрация
                    </a>
                  {% endif %}

                </div>
              </div>
            </nav>
          </div>
        </div>
      </div>
        <div class="wrap">
          <div class="row Header-rowMain">
            <div class="row-block Header-logo">
              <a class="logo" href="{% url 'index' %}">
                <img class="logo-image" src="{% static 'assets/img/logo.png' %}" alt="logo.png"/>
              </a>
            </div>
            <nav class="row-block row-block_right Header-menu">
              <div class="menuModal" id="navigate">
                <ul class="menu menu_main">
                  <li class="menu-item">
                    <a class="menu-link" href="{% url 'index' %}">
                      Главная
                    </a>
                  </li>
                  <li class="menu-item">
                    <span class="menu-label menu-label_success">
                      Скидки
                    </span>
                    <a class="menu-link" href="{% url 'products:catalog' %}">
                      Каталог
                    </a>
                  </li>
                  <li class="menu-item">
                    <a class="menu-link" href="{% url 'products:compare' %}">
                      Сравнение
                    </a>
                  </li>
                  <li class="menu-item">
                    <a class="menu-link" href="{% url 'products:sale' %}">
                      Скидки
                    </a>
                  </li>
                </ul>
              </div>
            </nav>
            <div class="row-block">
              <div class="CartBlock">

                {# User drop-down menu #}
                {% if user.is_authenticated %}
                  <div class="dropdown">
                    <button class="dropbtn">
                      <img class="CartBlock-img" src="{% static 'assets/img/icons/loon-icon.svg' %}" alt="loon-icon.svg"/>
                    </button>
                    <div class="dropdown-content">
                      <a class="dropdown-content-a" href="{% url 'users:account' %}">
                        Личный кабинет
                      </a>
                      {% if user.is_staff %}
                        <a class="dropdown-content-a" href="/admin/">
                          Административный раздел
                        </a>
                      {% endif %}
                      <a class="dropdown-content-a" href="{% url 'account_logout' %}">
                        Выход
                      </a>
                    </div>
                  </div>
                {% endif %}

                <a class="CartBlock-block" href="{% url 'products:cart_detail' %}">
                  <img class="CartBlock-img" src="{% static 'assets/img/icons/cart.svg' %}" alt="cart.svg"/>
                  <span class="CartBlock-amount">
                    {{ cart|length }}
                  </span>
                </a>
                <div class="CartBlock-block">
                  <span class="CartBlock-price">
                    {{ cart.get_total_products_price }} руб.
                  </span>
                </div>
              </div>
            </div>
            <div class="row-block Header-trigger">
              <a class="menuTrigger" href="#navigate">
                <div class="menuTrigger-content">
                  Показать навигацию
                </div>
                <span></span><span></span><span></span>
              </a>
            </div>
          </div>
        </div>
        <div class="Header-searchWrap">
          <div class="wrap">
            <div class="Header-categories">
              <div class="CategoriesButton">
                <div class="CategoriesButton-title">
                  <div class="CategoriesButton-icon">
                    <img src="{% static 'assets/img/icons/allDep.svg' %}" alt="allDep.svg"/>
                  </div>
                  <span class="CategoriesButton-text">
                    Все категории
                  </span>
                  <div class="CategoriesButton-arrow">
                  </div>
                </div>
                <div class="CategoriesButton-content">
                  {% for category in categories %}
                    <div class="CategoriesButton-link">
                      <a href="{% url 'products:catalog'%}?category={{ category.id }}" >
                        <div class="CategoriesButton-icon">
                          <img src="{{ category.image.url }}" alt="{{ category.title }}"/>
                        </div>
                        <span class="CategoriesButton-text">
                          {{ category.title }}
                        </span>
                      </a>
                    {% if category.subcategories.all.count %}
                      <a class="CategoriesButton-arrow" href="#"></a>
                      <div class="CategoriesButton-submenu">
                        {% for subcategory in category.subcategories.all %}
                        <a class="CategoriesButton-link" href="{% url 'products:catalog' %}?category={{ subcategory.id }}">
                          <div class="CategoriesButton-icon">
                            <img src="{{ subcategory.image.url }}" alt="{{ subcategory.title }}"/>
                          </div>
                          <span class="CategoriesButton-text">
                            {{ subcategory.title }}
                          </span>
                        </a>
                        {% endfor %}
                      </div>
                        {% endif %}
                      </div>
                    {% endfor %}
                </div>
              </div>
            </div>
            <div class="Header-searchLink">
              <img src="{% static 'assets/img/icons/search.svg' %}" alt="search.svg"/>
            </div>
            <div class="Header-search">
              <div class="search">
                <form class="form form_search" action="/products/catalog" method="GET">
                  {% csrf_token %}
                  <input class="search-input" id="query" name="query" type="text" placeholder="NVIDIA GeForce RTX 3060"/>
                  <button class="search-button" type="submit" name="search" id="search">
                    <img src="{% static 'assets/img/icons/search.svg' %}" alt="search.svg"/>
                    Поиск
                  </button>
                </form>
              </div>
            </div>
          </div>
        </div>
    </header>
{% endblock %}

{% block content %}
{% endblock %}

{% block footer %}
    <footer class="Footer">
      <div class="wrap">
        <div class="row Footer-main">
          <div class="row-block">
            <a class="logo Footer-logo" href="{% url 'index' %}">
              <img class="logo-image" src="{% static 'assets/img/logo_footer.png' %}" alt="logo_footer.png"/>
            </a>
          </div>
          <div class="row-block">
            <strong class="Footer-title">
              Навигация
            </strong>
            <ul class="menu menu_vt Footer-menu">
              <li class="menu-item">
                <a class="menu-link" href="{% url 'index' %}">
                  Главная
                </a>
              </li>
              <li class="menu-item">
                <a class="menu-link" href="{% url 'products:catalog' %}">
                  Каталог
                </a>
              </li>
              <li class="menu-item">
                <a class="menu-link" href="{% url 'products:compare' %}">
                  Сравнение
                </a>
              </li>
              <li class="menu-item">
                <a class="menu-link" href="{% url 'users:account' %}">
                  Профиль
                </a>
              </li>
            </ul>
          </div>
          <div class="row-block">
            <strong class="Footer-title">
              Контакты
            </strong>
            <p>
              Phone: 8.800.200.600<br>
              Email: xxx@meg.com<br>
            </p>
            <ul class="menu menu_img menu_smallImg Footer-menuSoc">
              <li class="menu-item">
                <a class="menu-link" href="#">
                  <img src="{% static 'assets/img/icons/socialFooter/fb.svg' %}" alt="fb.svg"/>
                </a>
              </li>
              <li class="menu-item">
                <a class="menu-link" href="#">
                  <img src="{% static 'assets/img/icons/socialFooter/tw.svg' %}" alt="tw.svg"/>
                </a>
              </li>
              <li class="menu-item">
                <a class="menu-link" href="#">
                  <img src="{% static 'assets/img/icons/socialFooter/in.svg' %}" alt="in.svg"/>
                </a>
              </li>
              <li class="menu-item">
                <a class="menu-link" href="#">
                  <img src="{% static 'assets/img/icons/socialFooter/pt.svg' %}" alt="pt.svg"/>
                </a>
              </li>
              <li class="menu-item">
                <a class="menu-link" href="#">
                  <img src="{% static 'assets/img/icons/socialFooter/mail.svg' %}" alt="mail.svg"/>
                </a>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </footer>
    <script src="{% static 'assets/plg/jQuery/jquery-3.5.0.slim.min.js' %}"></script>
    <script src="{% static 'assets/plg/form/jquery.form.js' %}"></script>
    <script src="{% static 'assets/plg/form/jquery.maskedinput.min.js' %}"></script>
    <script src="{% static 'assets/plg/range/ion.rangeSlider.min.js' %}"></script>
    <script src="{% static 'assets/plg/Slider/slick.min.js' %}"></script>
    <script src="{% static 'assets/js/scripts.js' %}"></script>
{% endblock %}

  </body>
</html>

templates/index.html
{% extends "base.html" %}
{% load static %}

{% block content %}
    <!-- Блок с баннерами -->
    {% if banners %}
      <div class="Header-slider">
        <div class="Slider Slider_main">
          <div class="Slider-box">
            {% for banner in banners %}
                  <div class ="Slider-item">
                      <div class ="Slider-content">
                          <div class ="row">
                              <div class ="row-block">
                                  <strong class ="Slider-title">
                                      {{banner.title}}
                                  </strong>
                                  <div class ="Slider-text">
                                      {{banner.content}}
                                  </div>
                                  <div class ="Slider-footer">
                                      <a class ="btn btn_primary" href="{{ banner.link }}">
                                          Get Started
                                      </a>
                                  </div>
                              </div>
                              <div class ="row-block">
                                  <div class ="Slider-img">
                                      <img src = "{{ banner.image.url }}"
                                           style = "width: 400px;"
                                           alt = "{{ banner.image.name }}"/>
                                  </div>
                              </div>
                          </div>
                      </div>
                  </div>
              {% endfor %}
          </div>
          <div class="Slider-navigateWrap">
            <div class="Slider-navigate">
            </div>
          </div>
        </div>
      </div>
    {% endif %}
    <div class="Middle">
        <div class="Section">
            <div class="wrap">

        <!-- Блок "ПРЕДЛОЖЕНИЕ ДНЯ" -->
        <div class="Section Section_column Section_columnLeft Section_columnDesktop">
            <div class="wrap">
                <div class="Section-column">
                    <div class="Section-columnSection Section-columnSection_mark">
                      {% if chosen_product %}
                        <header class="Section-columnHeader">
                          <strong class="Section-columnTitle">
                            ПРЕДЛОЖЕНИЕ ДНЯ
                          </strong>
                        </header>
                        <div class="Card">
                          <a class="Card-picture" href="{% url 'products:product' chosen_product.pk %}">
                            {% if chosen_product.images.count %}
                              <img src="{{ chosen_product.images.all.first.image_url }}" alt="{{ chosen_product.title }}"/>
                            {% else %}
                              <img src="{% static 'assets/img/product-placeholder.png' %}"
                                   alt="{{ chosen_product.title }}"/>
                            {% endif %}
                          </a>
                          <div class="Card-content">
                            <strong class="Card-title">
                              <a href="{% url 'products:product' chosen_product.pk %}">
                                {{ chosen_product.title }}
                              </a>
                            </strong>
                            <div class="Card-description">
                              <div class="Card-cost">
                                <span class="Card-price">
                                  ${{ chosen_product.get_avg_price_with_discount }}
                                </span>
                              </div>
                              <div class="Card-category">
                                {{ chosen_product.category }}
                              </div>
                            </div>
                            <div class="CountDown" data-date="{% now "d.m.Y" %} 23:59">
                              <div class="CountDown-block">
                                <div class="CountDown-wrap">
                                  <div class="CountDown-days">
                                  </div>
                                  <span class="CountDown-label">дни</span>
                                </div>
                              </div>
                              <div class="CountDown-block">
                                <div class="CountDown-wrap">
                                  <div class="CountDown-hours">
                                  </div>
                                  <span class="CountDown-label">часы</span>
                                </div>
                              </div>
                              <div class="CountDown-block">
                                <div class="CountDown-wrap">
                                  <div class="CountDown-minutes">
                                  </div>
                                  <span class="CountDown-label">мин</span>
                                </div>
                              </div>
                              <div class="CountDown-block">
                                <div class="CountDown-wrap">
                                  <div class="CountDown-secs">
                                  </div>
                                  <span class="CountDown-label">сек</span>
                                </div>
                              </div>
                            </div>
                          </div>
                        </div>
                      {% endif %}
                    </div>
                </div>

                <!-- Блок "Популярные товары" -->
                <div class="Section-content">
                    <header class="Section-header">
                        <h2 class="Section-title">Популярные товары</h2>
                    </header>
                    <div class="Cards">
                        {% for product in popular_products %}
							<div class="Card">
								<a class="Card-picture" href="{% url 'products:product' pk=product.pk %}">
									{% if product.images.count %}
										<img src="{{ product.images.all.first.image_url }}" alt="{{ product.title }}"/>
									{% else %}
										<img src="{% static 'assets/img/product-placeholder.png' %}"
											 alt="{{ product.title }}"/>
									{% endif %}
								</a>
                                <div class="Card-content">
                                    <strong class="Card-title">
                                        <a href="{% url 'products:product' pk=product.pk %}">
                                            {{ product.title|slice:":36" }}
                                        </a>
                                    </strong>
                                            <div class="Card-description">
                                                <div class="Card-cost">
                                                    <span class="Card-price">
                                                        {% if product.get_avg_price_with_discount == product.get_avg_price %}
															${{ product.get_avg_price_with_discount }}
														{% else %}
															<span style="text-decoration: line-through; color: rgb(66, 70, 80);">${{ product.get_avg_price }}</span> ${{ product.get_avg_price_with_discount }}
														{% endif %}
													</span>
                                                </div>

                                                <div class="Card-category">{{ product.category }}
                                                </div>
                                            </div>
                                </div>
                         </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>

				<!-- Блок "Ограниченный тираж" -->
        <div class="Section Section_column Section_columnRight">
            <div class="wrap">
                <div class="Section-content">
                    <div class="Slider Slider_carousel">
                        <header class="Section-header Section-header_close">
                            <h2 class="Section-title">Ограниченный тираж</h2>
                            <div class="Section-control">
                                <div class="Slider-navigate"></div>
                            </div>
                        </header>
                        <div class="Slider-box Cards">
                            {% for edition_product in limited_edition_products %}
                                <div class="Slider-item">
                                    <div class="Slider-content">
                                        <div class="Card">
                                            <a class="Card-picture" href="{% url 'products:product' pk=edition_product.pk %}">
												{% if edition_product.images.count %}
													<img src="{{ edition_product.images.all.first.image_url }}"
														 alt="{{ edition_product.title }}"/>
												{% else %}
													<img src="{% static 'assets/img/product-placeholder.png' %}"
														 alt="{{ edition_product.title }}"/>
												{% endif %}
											</a>
                                            <div class="Card-content">
                                                <strong class="Card-title">
                                                    <a href="{% url 'products:product' pk=edition_product.pk %}">
                                                        {{ edition_product.title|slice:":48" }}
                                                    </a>
                                                </strong>
                                                <div class="Card-description">
                                                    <div class="Card-cost">
                                                        <span class="Card-price">
															{% if edition_product.get_avg_price_with_discount == edition_product.get_avg_price %}
																${{ edition_product.get_avg_price_with_discount }}
															{% else %}
																<span style="text-decoration: line-through; color: rgb(66, 70, 80);">${{ edition_product.get_avg_price }}</span> ${{ edition_product.get_avg_price_with_discount }}
															{% endif %}
                                                        </span>
                                                    </div>
                                                    <div class="Card-category">{{ limited_product.category }}
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            {% endfor %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}