orders/urls.py
from django.urls import path

from orders.views import (CartView, CheckoutView, OrderDetailsView,
                          OrderListView, PaymentView, PaymentViewWithParams,
                          ProgressPaymentView)

app_name = "orders"
urlpatterns = [
    path("cart/", CartView.as_view(), name="cart"),
    path("checkout/", CheckoutView.as_view(), name="checkout"),
    path("payment/", PaymentView.as_view(), name="payment"),
    path("payment/<int:order_id>/", PaymentViewWithParams.as_view(), name="payment_with_params"),
    path("progress-payment", ProgressPaymentView.as_view(), name="progress-payment"),
    path("orders/", OrderListView.as_view(), name="orders"),
    path("orders/<int:pk>/", OrderDetailsView.as_view(), name="order_detail"),
]

products/urls.py
from django.urls import path

from products.views import (CartDetailView, CatalogView, CompareView,
                            ProductDetailsView, SaleView, add_to_comparison,
                            cart_add_product, cart_add_product_position,
                            cart_remove)

app_name = "products"
urlpatterns = [
    path("catalog/", CatalogView.as_view(), name="catalog"),
    path("catalog//<int:page>", CatalogView.listing, name="catalog-by-page"),
    path("product/<int:pk>/", ProductDetailsView.as_view(), name="product"),
    path("compare/", CompareView.as_view(), name="compare"),
    path("add_to_comparison/<int:pk>/", add_to_comparison, name="add_to_comparison"),
    path("sale/", SaleView.as_view(), name="sale"),
    path("cart/", CartDetailView.as_view(), name="cart_detail"),
    path(
        "cart/add/product/<int:product_id>/", cart_add_product, name="cart_add_product"
    ),
    path(
        "cart/add/product_position/<int:product_position_id>/",
        cart_add_product_position,
        name="cart_add_product_position",
    ),
    path("cart/remove/<int:product_position_id>/", cart_remove, name="cart_remove"),
]

store/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from products.views import IndexView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("allauth.urls")),
    path("", IndexView.as_view(), name="index"),
    path("products/", include("products.urls")),
    path("orders/", include("orders.urls")),
    path("users/", include("users.urls")),
    path("__debug__/", include("debug_toolbar.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path

from users.views import (AccountDetailView, ActionListView, EmailSentView,
                         EmailView, HistoryOrderView, PasswordView,
                         UserUpdateView)

app_name = "users"

urlpatterns = [
    path("account/", AccountDetailView.as_view(), name="account"),
    path("e-mail/", EmailView.as_view(), name="e-mail"),
    path("e-mail/sent/", EmailSentView.as_view(), name="email_sent"),
    path("password/", PasswordView.as_view(), name="password"),
    path("history-order/<int:pk>/", HistoryOrderView.as_view(), name="history_order"),
    path("profile/<int:pk>/", UserUpdateView.as_view(), name="profile"),
    path("viewhistory/", ActionListView.as_view(), name="viewhistory"),
]

orders/models.py
from django.db import models

from products.models import ProductPosition
from users.models import CustomUser


class Deliver(models.Model):
    """Model for storing delivery options."""

    title = models.CharField(
        verbose_name="название",
        max_length=512,
    )
    price = models.DecimalField(
        verbose_name="цена",
        max_digits=10,
        decimal_places=2,
    )
    free_threshold = models.DecimalField(
        verbose_name="порог бесплатной доставки",
        max_digits=10,
        decimal_places=2,
        null=True,
        blank=True,
    )
    is_express = models.BooleanField(
        verbose_name="экспресс доставка",
        default=False,
    )

    class Meta:
        ordering = ["title"]
        verbose_name = "доставка"
        verbose_name_plural = "доставки"

    def __str__(self):
        return self.title


class Order(models.Model):
    """Model for storing orders."""

    PAYMENT_CHOICES = (
        ("online", "Онлайн картой"),
        ("someone", "Онлайн со случайного чужого счета"),
    )

    STATUS_CHOICES = (
        ("created", "Сформирован"),
        ("unpaid", "Не оплачен"),
        ("paid", "Оплачен"),
        ("shipped", "В пути"),
        ("delivered", "Доставлен"),
        ("returned", "Возвращен"),
    )

    client = models.ForeignKey(
        CustomUser,
        verbose_name="клиент",
        on_delete=models.CASCADE,
        blank=True,
        null=True,
    )
    delivery = models.ForeignKey(
        Deliver,
        verbose_name="доставка",
        on_delete=models.SET_NULL,
        null=True,
    )
    delivery_price = models.DecimalField(
        verbose_name="стоимость доставки",
        max_digits=10,
        decimal_places=2,
        default=0,
    )
    payment = models.CharField(
        verbose_name="способ оплаты",
        max_length=10,
        choices=PAYMENT_CHOICES,
    )
    status = models.CharField(
        verbose_name="статус заказа",
        choices=STATUS_CHOICES,
        default="created",
        max_length=10,
    )
    name = models.CharField(
        verbose_name="имя",
        max_length=255,
    )
    phone = models.CharField(
        verbose_name="телефон",
        max_length=11,
    )
    email = models.EmailField(verbose_name="электронная почта")
    city = models.CharField(
        verbose_name="город",
        max_length=255,
    )
    address = models.CharField(
        verbose_name="адрес",
        max_length=512,
    )
    comment = models.CharField(
        verbose_name="комментарий к заказу",
        max_length=512,
        blank=True,
        null=True,
    )
    is_paid = models.BooleanField(
        verbose_name="оплачен",
        default=False,
    )
    is_deleted = models.BooleanField(
        verbose_name="удален",
        default=False,
    )
    created = models.DateTimeField(
        verbose_name="создан",
        auto_now_add=True,
    )
    updated = models.DateTimeField(
        verbose_name="обновлен",
        auto_now=True,
    )

    class Meta:
        ordering = ["-created"]
        verbose_name = "заказ"
        verbose_name_plural = "заказы"

    def __str__(self):
        return f"Заказ №{self.id}"

    @property
    def total_price(self):
        """Delivery price plus sum of all order item prices."""
        order_items = OrderItem.objects.filter(order=self)
        total_items_price = sum([item.price for item in order_items])
        return total_items_price + self.delivery_price


class OrderItem(models.Model):
    """Model for storing order items."""

    order = models.ForeignKey(
        Order,
        verbose_name="заказ",
        on_delete=models.CASCADE,
    )
    product_position = models.ForeignKey(
        ProductPosition,
        verbose_name="позиция товара",
        on_delete=models.CASCADE,
    )
    price = models.DecimalField(
        verbose_name="цена",
        max_digits=10,
        decimal_places=2,
    )
    quantity = models.PositiveIntegerField(verbose_name="количество")

    class Meta:
        verbose_name = "позиция заказа"
        verbose_name_plural = "позиции заказа"

    def __str__(self):
        return f"Order {self.order.id}, Product: {self.product_position}"

orders/forms.py
import re

from django import forms
from django.contrib.auth import authenticate

from users.models import CustomUser

from .models import Deliver, Order


class CheckoutStep1(forms.Form):
    name = forms.CharField(label="ФИО")
    phone = forms.CharField(label="Телефон")
    email = forms.EmailField(label="E-mail")
    password1 = forms.CharField(
        label="Пароль", required=False, widget=forms.PasswordInput()
    )
    password2 = forms.CharField(
        label="Повторите пароль", required=False, widget=forms.PasswordInput()
    )

    name.widget.attrs.update({"class": "form-input", "placeholder": "Ф.И.О."})
    phone.widget.attrs.update({"class": "form-input", "placeholder": "Номер телефона"})
    email.widget.attrs.update(
        {"class": "form-input", "placeholder": "username@domain.ru"}
    )
    password1.widget.attrs.update(
        {
            "class": "form-input",
            "placeholder": "Ваш пароль – для входа или регистрации",
        }
    )
    password2.widget.attrs.update(
        {
            "class": "form-input",
            "placeholder": "Повторите пароль – только для регистрации!",
        }
    )

    def clean_phone(self):
        phone_number = self.cleaned_data.get("phone")
        if phone_number:
            if not re.match(r"^(?:\+7|8)[0-9]{10}$", phone_number):
                raise forms.ValidationError("Неверный формат номера телефона")
        return phone_number

    def clean_email(self):
        email = self.data.get("email")
        password2 = self.data.get("password2")

        # Do not allow existing emails if user is trying to signup.
        if password2 and CustomUser.objects.filter(email=email).exists():
            raise forms.ValidationError("Пользователь с таким email уже существует!")

        return email

    def clean_password1(self):
        """Check if the user with email and password1 actually exists in database."""
        email = self.cleaned_data.get("email")
        password1 = self.data.get("password1")
        password2 = self.data.get("password2")

        if password2 and password2 != password1:
            raise forms.ValidationError("Введённые пароли должны совпадать!")

        if (
            password1
            and not password2
            and not authenticate(None, email=email, password=password1)
        ):
            raise forms.ValidationError("Пароль неверный.")

        return password1

    def clean_password2(self):
        password1 = self.data.get("password1")
        password2 = self.data.get("password2")
        if password2 and password2 != password1:
            raise forms.ValidationError("Введённые пароли должны совпадать!")
        return password2


class CheckoutStep2(forms.Form):
    delivery = None
    city = forms.CharField(label="Город")
    address = forms.CharField(
        label="Адрес",
        widget=forms.Textarea(
            attrs={"rows": 3, "class": "form-input", "placeholder": "Адрес доставки"}
        ),
    )

    city.widget.attrs.update({"class": "form-input", "placeholder": "Город доставки"})

    def __init__(self, *args, **kwargs):
        """Put all delivery options from the database into form field choices."""
        super().__init__(*args, **kwargs)
        deliveries = Deliver.objects.all()
        self.fields["delivery"] = forms.ChoiceField(
            label="Доставка",
            widget=forms.RadioSelect,
            choices=[(delivery.pk, delivery.title) for delivery in deliveries],
        )


class CheckoutStep3(forms.Form):
    payment = forms.ChoiceField(
        label="Способ оплаты",
        widget=forms.RadioSelect,
        choices=Order.PAYMENT_CHOICES,
    )


class CheckoutStep4(forms.Form):
    comment = forms.CharField(
        label="Комментарий к заказу",
        required=False,
        widget=forms.Textarea(
            attrs={
                "rows": 3,
                "class": "form-input",
                "placeholder": "Ваш комментарий к заказу",
            }
        ),
    )


class CardNumberForm(forms.Form):
    card_number = forms.CharField(required=True, widget=forms.TextInput(attrs={"class": "Payment-bill",
                                                                               "placeholder": "9999 9999",
                                                                               "data-mask": "9999 9999"}))

products/forms.py
from django import forms
from django.forms import ModelForm, Textarea

from products.models import Review


class ReviewCreationForm(ModelForm):
    class Meta:
        model = Review
        fields = ("body",)
        widgets = {
            "body": Textarea(attrs={"placeholder": "Отзыв", "class": "form-textarea"}),
        }


class ProductFilterForm(forms.Form):
    min_price = forms.DecimalField(required=False)
    max_price = forms.DecimalField(required=False)

    in_stock = forms.BooleanField(
        required=False,
        label="Только товары в наличии",
        widget=forms.CheckboxInput(attrs={})
    )

    free_shipping = forms.BooleanField(
        required=False,
        label="С бесплатной доставкой",
        widget=forms.CheckboxInput(attrs={})
    )

    product_name = forms.CharField(
        max_length=100,
        required=False,
        label="",
        widget=forms.TextInput(attrs={"class": "form-input form-input_full", "placeholder": "Название"})
    )


class AddProductToCartForm(forms.Form):
    """
    Form to add products to the cart or override quantity of product_position already  in the cart.
    """

    quantity = forms.IntegerField()
    is_override = forms.BooleanField(
        required=False, initial=False, widget=forms.HiddenInput
    )

templates/orders/cart.html
{% extends "base.html" %}
{% load static %}

{% block content %}
  <div class="Middle Middle_top">
    <div class="Section">
      <div class="wrap">
        {% if cart|length %}
        <div class="form Cart">

          {% for item in cart %}
            <div class="Cart-product">
              <div class="Cart-block Cart-block_row">
                <div class="Cart-block Cart-block_pict">
                  <a class="Cart-pict" href="{% url 'products:product' item.product_position.product.pk %}">
                    {% with item.product_position.product.images.all|first as img %}
                      {% if img %}
                        <img class="Cart-img" src="{{ img.image_url }}" alt="{{ item.product_position }}" />
                      {% else %}
                        <img class="Cart-img" src="{% static "assets/img/product-placeholder.png" %}" alt="{{ item.product_position }}" />
                      {% endif %}
                    {% endwith %}
                  </a>
                </div>
                <div class="Cart-block Cart-block_info">
                  <a class="Cart-title" href="{% url 'products:product' item.product_position.product.pk %}">
                    {{ item.product_position }}
                  </a>
                  <div class="Cart-desc">
                    {{ item.product_position.product.description|truncatechars:512 }}
                  </div>
                </div>
                <div class="Cart-block Cart-block_price">
                  <div class="Cart-price">
                    {{ item.total_price }}
                  </div>
                </div>
              </div>

              <div class="Cart-block Cart-block_row">
                <div class="Cart-block Cart-block_seller">
                </div>
                <div class="Cart-block Cart-block_amount">
                  <div class="Cart-amount">
                    <form action="{% url 'products:cart_add_product_position' item.product_position.id %}" method="post">
                      {% csrf_token %}
                      <div class="Amount">
                        <button class="Amount-remove" type="button">
                        </button>
                        <input class="Amount-input form-input" name="quantity" type="text" value="{{ item.quantity }}" id="id_quantity" required />
                        <input type="hidden" name="is_override" id="id_is_override" value="True">
                        <button class="Amount-add" type="button">
                        </button>
                      </div>
                      <button type="submit">
                        Пересчитать
                      </button>
                    </form>
                  </div>
                </div>
                <div class="Cart-block Cart-block_delete">
                  <form action="{% url 'products:cart_remove' item.product_position.pk %}" method="post">
                    {% csrf_token %}
                    <button class="Cart-delete" type="submit">
                      <img src="{% static 'assets/img/icons/card/delete.svg' %}" alt="Удалить товар из корзины" />
                    </button>
                  </form>
                </div>
              </div>

            </div>
          {% endfor %}

          <div class="Cart-total">
            <div class="Cart-block Cart-block_total">
              <strong class="Cart-title">
                Итого:
              </strong>
              <span class="Cart-price">
                {{ cart.get_total_products_price }}
              </span>
            </div>
            <div class="Cart-block">
              <a class="btn btn_success btn_lg" href="{% url 'orders:checkout' %}">
                Оформить заказ
              </a>
            </div>
          </div>
        </div>
        {% else %}
          <h2>Ваша корзина пока пуста!</h2>
        {% endif %}
      </div>
    </div>
  </div>
{% endblock %}

templates/orders/checkout.html
{% extends "base.html" %}
{% load static %}

{% block content %}
  <div class="Middle Middle_top">
    <div class="Section Section_column Section_columnRight Section_columnWide Order">
      <div class="wrap">
        <div class="Section-column">
          <div class="Section-columnSection">
            <header class="Section-header">
              <strong class="Section-title">
                Прогресс заполнения
              </strong>
            </header>
            <div class="Section-columnContent">
              <div class="NavigateProfile">
                <ul class="menu menu_vt">
                  <li
                    {% if step == "1" %}
                      class="menu-item_ACTIVE menu-item"
                    {% else %}
                      class="menu-item"
                    {% endif %}
                  >
                    <a class="menu-link" href="{% url 'orders:checkout' %}?step=1">
                      Шаг 1. Параметры пользователя
                    </a>
                  </li>
                  {% if step == "2" or step == "3" or step == "4" %}
                    <li
                      {% if step == "2" %}
                        class="menu-item_ACTIVE menu-item"
                      {% else %}
                        class="menu-item"
                      {% endif %}
                    >
                      <a class="menu-link" href="{% url 'orders:checkout' %}?step=2">
                        Шаг 2. Способ доставки
                      </a>
                    </li>
                  {% endif %}
                  {% if step == "3" or step == "4" %}
                    <li
                      {% if step == "3" %}
                        class="menu-item_ACTIVE menu-item"
                      {% else %}
                        class="menu-item"
                      {% endif %}
                    >
                      <a class="menu-link" href="{% url 'orders:checkout' %}?step=3">
                        Шаг 3. Способ оплаты
                      </a>
                    </li>
                  {% endif %}
                  {% if step == "4" %}
                    <li
                      {% if step == "4" %}
                        class="menu-item_ACTIVE menu-item"
                      {% else %}
                        class="menu-item"
                      {% endif %}
                    >
                      <a class="menu-link" href="{% url 'orders:checkout' %}?step=4">
                        Шаг 4. Подтверждение заказа
                      </a>
                    </li>
                  {% endif %}
                </ul>
              </div>
            </div>
          </div>
        </div>

        <div class="Section-content">

          {% if step == "1" %}
            <form class="form" action="{% url 'orders:checkout' %}?step=1" method="post">
              {% csrf_token %}
              <div class="Order-block Order-block_OPEN" id="step1">
                <header class="Section-header Section-header_sm">
                  <h2 class="Section-title">
                    Шаг 1. Параметры пользователя
                  </h2>
                </header>
                <div class="row">
                  <div class="row-block">

                    <!-- Step 1 - auto-generated form -->
                    {% for field in form %}
                      {% if field.auto_id != "id_password1" and field.auto_id != "id_password2" %}
                        <div class="form-group">
                          <label class="form-label" for="{{ field.auto_id }}">
                            {{ field.label }}
                          </label>
                          {{ field }}
                          <span style="color: red;">
                            {{ field.errors }}
                          </span>
                        </div>
                      {% endif %}
                    {% endfor %}
                  </div>

                  <div class="row-block">
                    {% if not user.is_authenticated %}
                      {% for field in form %}
                        {% if field.auto_id == "id_password1" or field.auto_id == "id_password2" %}
                          <div class="form-group">
                            <label class="form-label" for="{{ field.auto_id }}">
                              {{ field.label }}
                            </label>
                            {{ field }}
                            <span style="color: red;">
                              {{ field.errors }}
                            </span>
                          </div>
                        {% endif %}
                      {% endfor %}

                      <div class="form-group">
                        <a class="btn btn_muted Order-btnReg" href="#">
                         Я уже зарегистрирован
                        </a>
                      </div>
                    {% endif %}
                  </div>
                </div>
                <div class="Order-footer">
                  <button class="btn btn_success" type="submit">
                    Дальше
                  </button>
                </div>
              </div>
            </form>
          {% endif %}

          {% if step == "2" %}
            <form class="form" action="{% url 'orders:checkout' %}?step=2" method="post">
              {% csrf_token %}
                <div class="Order-block Order-block_OPEN" id="step2">
                <header class="Section-header Section-header_sm">
                  <h2 class="Section-title">
                    Шаг 2. Способ доставки
                  </h2>
                </header>

                <!-- Step 2 - auto-generated form -->
                {% for field in form %}
                  <div class="form-group">
                    <label class="form-label" for="{{ field.auto_id }}">
                      {{ field.label }}
                    </label>
                    {{ field }}
                  </div>
                {% endfor %}

                <div class="Order-footer">
                  <button class="btn btn_success" type="submit">
                    Дальше
                  </button>
                </div>
              </div>
            </form>
          {% endif %}

          {% if step == "3" %}
            <form class="form" action="{% url 'orders:checkout' %}?step=3" method="post">
              {% csrf_token %}
              <div class="Order-block Order-block_OPEN" id="step3">
                <header class="Section-header Section-header_sm">
                  <h2 class="Section-title">
                    Шаг 3. Способ оплаты
                  </h2>
                </header>

                <!-- Step 3 - auto-generated form -->
                {% for field in form %}
                  <div class="form-group">
                    <label class="form-label" for="{{ field.auto_id }}">
                      {{ field.label }}
                    </label>
                    {{ field }}
                  </div>
                {% endfor %}

                <div class="Order-footer">
                  <button class="btn btn_success" type="submit">
                    Дальше
                  </button>
                </div>
              </div>
            </form>
          {% endif %}

          {% if step == "4" %}
            <div class="Order-block Order-block_OPEN" id="step4">
              <header class="Section-header Section-header_sm">
                <h2 class="Section-title">
                  Шаг 4. Подтверждение заказа
                </h2>
              </header>
              <div class="Order-infoBlock">
                <div class="Order-personal">
                  <div class="row">
                    <div class="row-block">
                      <div class="Order-info">
                        <div class="Order-infoType">
                          ФИО:
                        </div>
                        <div class="Order-infoContent">
                          {{ order.name }}
                        </div>
                      </div>
                      <div class="Order-info">
                        <div class="Order-infoType">
                          Телефон:
                        </div>
                        <div class="Order-infoContent">
                          {{ order.phone }}
                        </div>
                      </div>
                      <div class="Order-info">
                        <div class="Order-infoType">
                          E-mail:
                        </div>
                        <div class="Order-infoContent">
                          {{ order.email }}
                        </div>
                      </div>
                    </div>
                    <div class="row-block">
                      <div class="Order-info Order-info_delivery">
                        <div class="Order-infoType">
                          Тип доставки:
                        </div>
                        <div class="Order-infoContent">
                          {{ order.delivery }}
                        </div>
                      </div>
                      <div class="Order-info">
                        <div class="Order-infoType">
                          Город:
                        </div>
                        <div class="Order-infoContent">
                          {{ order.city }}
                        </div>
                      </div>
                      <div class="Order-info">
                        <div class="Order-infoType">
                          Адрес:
                        </div>
                        <div class="Order-infoContent">
                          {{ order.address }}
                        </div>
                      </div>
                      <div class="Order-info Order-info_pay">
                        <div class="Order-infoType">
                          Оплата:
                        </div>
                        <div class="Order-infoContent">
                          {{ order.payment }}
                        </div>
                      </div>
                    </div>
                  </div>
                </div>

                <div class="Cart Cart_order">

                  {% for item in cart  %}
                    <div class="Cart-product">
                      <div class="Cart-block Cart-block_row">
                        <div class="Cart-block Cart-block_pict">
                          <a class="Cart-pict" href="{% url 'products:product' item.product_position.product.pk %}">
                            {% with item.product_position.product.images.all|first as img %}
                              {% if img %}
                                <img class="Cart-img" src="{{ img.image_url }}" alt="{{ item.product_position }}" />
                              {% else %}
                                <img class="Cart-img" src="{% static "assets/img/product-placeholder.png" %}" alt="{{ item.product_position }}" />
                              {% endif %}
                            {% endwith %}
                          </a>
                        </div>
                        <div class="Cart-block Cart-block_info">
                          <a class="Cart-title" href="{% url 'products:product' item.product_position.product.pk %}">
                            {{ item.product_position }}
                          </a>
                          <div class="Cart-desc">
                            {{ item.product_position.product.description|truncatechars:256 }}
                          </div>
                        </div>
                        <div class="Cart-block Cart-block_price">
                          <div class="Cart-price">
                            {{ item.total_price }}
                          </div>
                        </div>
                      </div>
                      <div class="Cart-block Cart-block_row">
                        <div class="Cart-block Cart-block_amount">
                          {{ item.quantity }}
                        </div>
                      </div>
                    </div>
                  {% endfor %}

                  <form class="form" action="{% url 'orders:checkout' %}?step=4" method="post">
                    {% csrf_token %}
                    <!-- Step 4 - auto-generated form -->
                    {% for field in form %}
                      <div class="form-group">
                        <label class="form-label" for="{{ field.auto_id }}">
                          {{ field.label }}
                        </label>
                        {{ field }}
                      </div>
                    {% endfor %}

                    <div class="Cart-total">
                      <div class="Cart-block Cart-block_total">
                        <strong class="Cart-title">
                          Итого:
                        </strong>
                        <span class="Cart-price">
                          {{ order.total_price }}
                        </span>
                        Доставка: {{ order.delivery_price }}
                        Товары: {{ cart.get_total_products_price }}
                      </div>
                      <div class="Cart-block">
                        <button class="btn btn_primary btn_lg" type="submit">
                          Оплатить
                        </button>
                      </div>
                    </div>
                  </form>
                </div>
              </div>
            </div>
          {% endif %}

        </div>
      </div>
    </div>
  </div>
{% endblock %}

templates/orders/payment.html
{% extends "base.html" %}
{% load static %}

{% block content %}
    <div class="Middle Middle_top">
        <div class="Section">
            <div class="wrap">
                <form class="form Payment" action="{% url 'orders:payment' %}" method="post">
                    <div class="Payment-card">
                        <div class="form-group">
                            <label class="form-label">Номер карты</label>
                            {% csrf_token %}
                            {{ form.card_number }}
                        </div>
                    </div>
                    <div class="Payment-pay"><button class="btn btn_primary" type="submit">Оплатить</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}