orders/urls.py
from django.urls import path

from orders.views import (CartView, CheckoutView, OrderDetailsView,
                          OrderListView, PaymentView, PaymentViewWithParams,
                          ProgressPaymentView)

app_name = "orders"
urlpatterns = [
    path("cart/", CartView.as_view(), name="cart"),
    path("checkout/", CheckoutView.as_view(), name="checkout"),
    path("payment/", PaymentView.as_view(), name="payment"),
    path("payment/<int:order_id>/", PaymentViewWithParams.as_view(), name="payment_with_params"),
    path("progress-payment", ProgressPaymentView.as_view(), name="progress-payment"),
    path("orders/", OrderListView.as_view(), name="orders"),
    path("orders/<int:pk>/", OrderDetailsView.as_view(), name="order_detail"),
]

products/urls.py
from django.urls import path

from products.views import (CartDetailView, CatalogView, CompareView,
                            ProductDetailsView, SaleView, add_to_comparison,
                            cart_add_product, cart_add_product_position,
                            cart_remove)

app_name = "products"
urlpatterns = [
    path("catalog/", CatalogView.as_view(), name="catalog"),
    path("catalog//<int:page>", CatalogView.listing, name="catalog-by-page"),
    path("product/<int:pk>/", ProductDetailsView.as_view(), name="product"),
    path("compare/", CompareView.as_view(), name="compare"),
    path("add_to_comparison/<int:pk>/", add_to_comparison, name="add_to_comparison"),
    path("sale/", SaleView.as_view(), name="sale"),
    path("cart/", CartDetailView.as_view(), name="cart_detail"),
    path(
        "cart/add/product/<int:product_id>/", cart_add_product, name="cart_add_product"
    ),
    path(
        "cart/add/product_position/<int:product_position_id>/",
        cart_add_product_position,
        name="cart_add_product_position",
    ),
    path("cart/remove/<int:product_position_id>/", cart_remove, name="cart_remove"),
]

store/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from products.views import IndexView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("allauth.urls")),
    path("", IndexView.as_view(), name="index"),
    path("products/", include("products.urls")),
    path("orders/", include("orders.urls")),
    path("users/", include("users.urls")),
    path("__debug__/", include("debug_toolbar.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path

from users.views import (AccountDetailView, ActionListView, EmailSentView,
                         EmailView, HistoryOrderView, PasswordView,
                         UserUpdateView)

app_name = "users"

urlpatterns = [
    path("account/", AccountDetailView.as_view(), name="account"),
    path("e-mail/", EmailView.as_view(), name="e-mail"),
    path("e-mail/sent/", EmailSentView.as_view(), name="email_sent"),
    path("password/", PasswordView.as_view(), name="password"),
    path("history-order/<int:pk>/", HistoryOrderView.as_view(), name="history_order"),
    path("profile/<int:pk>/", UserUpdateView.as_view(), name="profile"),
    path("viewhistory/", ActionListView.as_view(), name="viewhistory"),
]

users/models.py
from django.contrib.auth.models import AbstractUser
from django.contrib.contenttypes.fields import GenericForeignKey
from django.contrib.contenttypes.models import ContentType
from django.db import models
from django.db.models.signals import pre_save
from django.dispatch import receiver


def get_default_profile_image():
    return "../static/assets/img/icons/loon-icon.svg"


class CustomUser(AbstractUser):
    """Represents user of the shop."""

    middle_name = models.CharField(
        verbose_name="отчество",
        max_length=20,
        null=True,
        blank=True,
    )
    image = models.ImageField(
        verbose_name="изображение профиля",
        upload_to="avatars/",
        blank=True,
        null=False,
        default=get_default_profile_image,
    )
    phone = models.CharField(
        verbose_name="телефон",
        max_length=11,
        null=True,
        blank=True,
    )

    class Meta:
        ordering = ["id"]
        indexes = [
            models.Index(fields=["id"]),
        ]
        verbose_name = "пользователь"
        verbose_name_plural = "пользователи"

    def get_full_name(self):
        full_name = f"{self.first_name} {self.middle_name} {self.last_name}".strip()
        return full_name

    def __str__(self):
        return self.email


@receiver(pre_save, sender=CustomUser)
def delete_old_image(sender, instance, **kwargs):
    if not instance.pk:
        return

    old_image_name = CustomUser.objects.get(pk=instance.pk)
    if old_image_name.image.name == "../static/assets/img/icons/loon-icon.svg":
        return

    if instance.pk:
        try:
            old_image = CustomUser.objects.get(pk=instance.pk).image

        except CustomUser.DoesNotExist:
            return

        if old_image and old_image.url != instance.image.url:
            storage, path = old_image.storage, old_image.path
            try:
                storage.delete(path)
            except Exception:
                return


class Action(models.Model):
    """
    Model to store user actions in connection with "target" database models.

    user: user who made the action
    verb: what was done; use constants from Action model
    created: date/time of action
    target_ct: this will tell us the model for the relationship
    target_id: a field to store primary key of the related object
    target: a field to define and manage the generic relation using two previous fields
    """

    VIEW_PRODUCT = "просмотрен товар"

    user = models.ForeignKey(
        verbose_name="пользователь",
        to=CustomUser,
        related_name="actions",
        on_delete=models.CASCADE,
    )
    verb = models.CharField(
        verbose_name="действие",
        max_length=256,
    )
    target_ct = models.ForeignKey(
        ContentType,
        blank=True,
        null=True,
        related_name="target_obj",
        on_delete=models.CASCADE,
    )
    target_id = models.PositiveIntegerField(
        null=True,
        blank=True,
    )
    target = GenericForeignKey(
        ct_field="target_ct",
        fk_field="target_id",
    )
    created = models.DateTimeField(
        verbose_name="время события",
        auto_now_add=True,
    )

    class Meta:
        verbose_name = "действие"
        verbose_name_plural = "действия"
        ordering = ["-created"]

users/forms.py
import re

from django import forms
from django.contrib.auth.forms import UserChangeForm, UserCreationForm

from users.models import CustomUser


class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = CustomUser
        fields = ("username", "email")


class CustomUserChangeForm(UserChangeForm):
    full_name = forms.CharField(
        max_length=255, label="ФИО",
        widget=forms.TextInput(attrs={"placeholder": "Введите полное имя"})
    )
    image = forms.ImageField(
        required=False,
        widget=forms.FileInput(attrs={"class": "Profile-file form-input"})
    )
    email = forms.EmailField(
        max_length=255, required=False, label="Адрес эл. почты",
        widget=forms.EmailInput(attrs={"placeholder": "Введите адрес эл. почты"})
    )
    phone = forms.CharField(
        label="Введите номер телефона",
        widget=forms.TextInput(attrs={"placeholder": "89881234567"})
    )

    class Meta:
        model = CustomUser
        fields = ("image", "email", "phone")

    def clean_full_name(self):
        full_name = self.cleaned_data.get("full_name")
        if full_name:
            try:
                first_name, middle_name, last_name = full_name.split(" ", 2)
                self.instance.first_name = first_name
                self.instance.middle_name = middle_name
                self.instance.last_name = last_name
            except ValueError:
                raise forms.ValidationError("Неверный формат ФИО")
        return full_name

    def clean_phone(self):
        phone_number = self.cleaned_data.get("phone")
        if phone_number:
            if not re.match(r"^(?:\+7|8)[0-9]{10}$", phone_number):
                raise forms.ValidationError("Неверный формат номера телефона")
        return phone_number

    def clean_image(self):
        image = self.cleaned_data.get("image")
        if image.name == "../static/assets/img/icons/loon-icon.svg":
            return image
        if image:
            if hasattr(image, "size"):
                if image.size > 2 * 1024 * 1024:
                    raise forms.ValidationError("Файл слишком большой. Максимальный размер - 2 МБ.")
        return image


class CustomUserChangeFormAdmin(UserChangeForm):
    image = forms.ImageField(
        required=False,
        widget=forms.FileInput(attrs={"class": "Profile-file form-input"})
    )
    email = forms.EmailField(
        max_length=255, required=False, label="Адрес эл. почты",
        widget=forms.EmailInput(attrs={"placeholder": "Введите адрес эл. почты"})
    )
    phone = forms.CharField(
        required=False,
        label="Введите номер телефона",
        widget=forms.TextInput(attrs={"placeholder": "89881234567"})
    )

    class Meta:
        model = CustomUser
        fields = ("image", "email", "phone")

    def clean_phone(self):
        phone_number = self.cleaned_data.get("phone")
        if phone_number:
            if not re.match(r"^(?:\+7|8)[0-9]{10}$", phone_number):
                raise forms.ValidationError("Неверный формат номера телефона")
        return phone_number

    def clean_image(self):
        image = self.cleaned_data.get("image")
        if image.name == "../static/assets/img/icons/loon-icon.svg":
            return image
        if image:
            if hasattr(image, "size"):
                if image.size > 2 * 1024 * 1024:
                    raise forms.ValidationError("Файл слишком большой. Максимальный размер - 2 МБ.")
        return image

users/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.cache import cache
from django.core.mail import send_mail
from django.http import HttpResponseRedirect, JsonResponse
from django.urls import reverse, reverse_lazy
from django.utils import timezone
from django.utils.crypto import get_random_string
from django.views.generic import TemplateView, UpdateView

from orders.models import Order
from users.forms import CustomUserChangeForm
from users.models import Action, CustomUser


class AccountDetailView(LoginRequiredMixin, TemplateView):
    template_name = "users/account.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["user"] = self.request.user
        context["latest_order"] = Order.objects.filter(client_id=self.request.user).order_by("-created").first()
        context["actions"] = Action.objects.filter(verb=Action.VIEW_PRODUCT, user=self.request.user)[:3]
        return context


class EmailView(TemplateView):
    template_name = "users/e-mail.html"

    def post(self, request, *args, **kwargs):
        email = request.POST.get("email")
        last_request_time = cache.get(f"last_request_{email}")

        user_exists = CustomUser.objects.filter(email=email).exists()
        if not user_exists:
            request.session["time_limit_error"] = "Введенный e-mail не найден."
            return HttpResponseRedirect(reverse("users:e-mail"))

        if last_request_time and (timezone.now() - last_request_time).total_seconds() < 60:
            request.session["time_limit_error"] = "Вы не можете запрашивать проверочный код чаще одного раза в минуту."
            return HttpResponseRedirect(reverse("users:e-mail"))

        reset_code = get_random_string(length=6, allowed_chars="0123456789")
        reset_url = request.build_absolute_uri(f"{reverse('users:password')}?code={reset_code}")

        cache.set(f"email_for_code_{reset_code}", email, 3600)
        cache.set(f"reset_code_{email}", reset_code, 3600)
        cache.set(f"last_request_{email}", timezone.now(), 3600)

        send_mail(
            "Восстановление пароля",
            f"Ваш код для восстановления пароля: {reset_code}\n"
            f"Или перейдите по ссылке: {reset_url}",
            "from@example.com",
            [email],
            fail_silently=False,
        )

        if "time_limit_error" in request.session:
            del request.session["time_limit_error"]

        return HttpResponseRedirect(reverse("users:email_sent"))


class EmailSentView(TemplateView):
    template_name = "users/e-mail_sent.html"


class PasswordView(TemplateView):
    template_name = "users/password.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        code = self.request.GET.get("code")
        context["code"] = code
        return context

    def get(self, request, *args, **kwargs):
        code = request.GET.get("code")
        email = cache.get(f"email_for_code_{code}")

        if email and cache.get(f"reset_code_{email}") == code:
            return super().get(request, *args, **kwargs)
        else:
            return JsonResponse({"status": "error", "message": "Invalid or expired code."})

    def post(self, request, *args, **kwargs):
        new_password = request.POST.get("pass")
        code = request.GET.get("code")
        email = cache.get(f"email_for_code_{code}")

        if email and cache.get(f"reset_code_{email}") == code:
            user = CustomUser.objects.get(email=email)
            user.set_password(new_password)  # Используем set_password для безопасности
            user.save()

            cache.delete(f"reset_code_{email}")
            cache.delete(f"email_for_code_{code}")

            return HttpResponseRedirect(reverse("account_login"))
        else:
            return JsonResponse({"status": "error", "message": "Invalid or expired code."})


class HistoryOrderView(TemplateView):
    template_name = "users/historyorder.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["user"] = self.request.user
        context["orders"] = Order.objects.filter(client_id=self.request.user)

        return context


class UserUpdateView(LoginRequiredMixin, UpdateView):
    model = CustomUser
    form_class = CustomUserChangeForm
    template_name = "users/profile.html"
    success_url = reverse_lazy("users:account")

    def get_initial(self):
        initial = super().get_initial()
        initial["full_name"] = self.request.user.get_full_name()
        return initial


class ActionListView(LoginRequiredMixin, TemplateView):
    template_name = "users/viewhistory.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["actions"] = Action.objects.filter(verb=Action.VIEW_PRODUCT, user=self.request.user)[:20]
        return context

templates/users/account.html
{% extends "users/base-account.html" %}
{% load static %}
{% block account_section %}
    <div class="Section-content">
        <div class="Account">
            <div class="Account-group">
                <div class="Account-column">
                    <div class="Account-avatar"><img src="{{ user.image.url }}" alt="avatar.jpg"/>
                    </div>
                </div>
                <div class="Account-column">
                    <div class="Account-name">
                        {% if user.get_full_name != 'None' %} {{ user.get_full_name }} {% else %} {{ user.email }} {% endif %}
                    </div>
                    <a class="Account-editLink" href="{% url 'users:profile' pk=user.pk %}">Редактировать профиль</a>
                </div>
            </div>
            <div class="Account-group">
                <div class="Account-column Account-column_full">
                {% if latest_order and latest_order.id %}
                    <div class="Order Order_anons">
                        <div class="Order-personal">
                            <div class="row">
                                <div class="row-block">
                                    <a class="Order-title" href="{% url 'orders:order_detail' pk=latest_order.id %}">
                                        Заказ&#32;
                                        <span class="Order-numberOrder">№{{ latest_order.id }}</span>&#32;от&#32;
                                        <span class="Order-dateOrder">{{ latest_order.created|date:"d.m.Y" }}</span>
                                    </a>
                                    <div class="Account-editLink">
                                        <a href="{% url 'users:history_order' user.id %}">История заказов</a>
                                    </div>
                                </div>
                                <div class="row-block">
                                    <div class="Order-info Order-info_delivery">
                                        <div class="Order-infoType">Тип доставки:
                                        </div>
                                        <div class="Order-infoContent">
                                            {% if latest_order.delivery_id == 1 %}
                                                Обычная доставка
                                            {% else %}
                                                Экспресс доставка
                                            {% endif %}
                                        </div>
                                    </div>
                                    <div class="Order-info Order-info_pay">
                                        <div class="Order-infoType">Оплата:
                                        </div>
                                        <div class="Order-infoContent">
                                            {% if latest_order.payment == 'someone' %}
                                                Онлайн со случайного чужого счета
                                            {% else %}
                                                Онлайн картой
                                            {% endif %}
                                        </div>
                                    </div>
                                    <div class="Order-info">
                                        <div class="Order-infoType">Общая стоимость:
                                        </div>
                                        <div class="Order-infoContent">{{ latest_order.total_price }}$
                                        </div>
                                    </div>
                                    <div class="Order-info Order-info_status">
                                        <div class="Order-infoType">Статус:
                                        </div>
                                        <div class="Order-infoContent">
                                            {% if latest_order.status == 'created' %}
                                                Сформирован
                                            {% elif latest_order.status == 'unpaid' %}
                                                Не оплачен
                                            {% elif latest_order.status == 'paid' %}
                                                Оплачен
                                            {% elif latest_order.status == 'shipped' %}
                                                В пути
                                            {% elif latest_order.status == 'delivered' %}
                                                Доставлен
                                            {% elif latest_order.status == 'returned' %}
                                                Возвращен
                                            {% endif %}
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                {% endif %}
                {% if actions %}
                    <BR><BR>
                    <div>
                        <div><a href="{% url 'users:viewhistory' %}">История просмотров:</a></div>
                        <div class="Cards">
                            {% for action in actions %}
                                <div class="Card">
                                    <a class="Card-picture" href="{% url 'products:product' action.target_id %}">
                                        {% if action.target.images.count %}
                                            <img src="{{ action.target.images.all.first.image_url }}"
                                                 alt="{{ action.target.title }}"/>
                                        {% else %}
                                            <img src="{% static 'assets/img/product-placeholder.png' %}"
                                                 alt="{{ action.target.title }}"/>
                                        {% endif %}
                                    </a>
                                    <div class="Card-content">
                                        <strong class="Card-title">
                                            <a href="{% url 'products:product' action.target_id %}">{{ action.target.title }}</a>
                                        </strong>
                                        <div class="Card-description">
                                            <div class="Card-cost">
                                                {% if action.target.get_new_price_and_sale.new_price %}
                                                    <span class="Card-priceOld">${{ action.target.get_old_price }}</span>
                                                    <span class="Card-price">${{ action.target.get_new_price_and_sale.new_price|default:"NONE" }}</span>
                                                {% else %}
                                                    <span class="Card-price">${{ action.target.get_old_price }}</span>
                                                {% endif %}
                                            </div>
                                            <div class="Card-category">{{ action.target.category }}
                                            </div>
                                            <div class="Card-hover">
                                                {#                                <a class="Card-btn" href="#">#}
                                                {#                                    <img src="{% static 'assets/img/icons/card/bookmark.svg' %}" alt="bookmark.svg"/>#}
                                                {#                                </a>#}
                                                <a class="Card-btn"
                                                   href="{% url 'products:product' action.target_id %}">
                                                    <img src="{% static 'assets/img/icons/card/cart.svg' %}"
                                                         alt="cart.svg"/>
                                                </a>
                                                <a class="Card-btn"
                                                   href="{% url 'products:add_to_comparison' pk=action.target_id %}">
                                                    <img src="{% static 'assets/img/icons/card/change.svg' %}"
                                                         alt="change.svg"/>
                                                </a>
                                            </div>
                                        </div>
                                    </div>
                                    {% if action.target.get_new_price_and_sale.sale %}
                                        <div class="Card-sale">
                                            {{ action.target.get_new_price_and_sale.sale }}
                                        </div>
                                    {% else %}
                                    {% endif %}
                                </div>
                            {% endfor %}
                        </div>
                    </div>
                {% endif %}
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/users/base-account.html
{% extends "base.html" %}

{% block content %}
    <div class="Middle Middle_top">
        <div class="Section Section_column Section_columnLeft">
            <div class="wrap">
                <div class="Section-column">
                    <div class="Section-columnSection">
                        <header class="Section-header">
                            <strong class="Section-title">Навигация
                            </strong>
                        </header>
                        <div class="Section-columnContent">
                            <div class="NavigateProfile">
                                <ul class="menu menu_vt">
                                    <li class="menu-item">
                                        <a class="menu-link" href="{% url 'users:account' %}">Личный кабинет</a>
                                    </li>
                                    <li class="menu-item">
                                        <a class="menu-link" href="{% url 'users:profile' user.id %}">Профиль</a>
                                    </li>
                                    <li class="menu-item">
                                        <a class="menu-link" href="{% url 'users:history_order' user.id %}">История заказов</a>
                                    </li>
                                    <li class="menu-item">
                                        <a class="menu-link" href="{% url 'users:viewhistory' %}">История просмотров</a>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
                {% block account_section %} {% endblock %}
            </div>
        </div>
    </div>
{% endblock %}

templates/users/viewhistory.html
{% extends "users/base-account.html" %}
{% load static %}
{% block account_section %}
    <div class="Section-content">
        <div class="Cards">
            {% for action in actions %}
                <div class="Card">
                    <a class="Card-picture" href="{% url 'products:product' action.target_id %}">
                        {% if action.target.images.count %}
                            <img src="{{ action.target.images.all.first.image_url }}" alt="{{ action.target.title }}"/>
                        {% else %}
                            <img src="{% static 'assets/img/product-placeholder.png' %}"
                                 alt="{{ action.target.title }}"/>
                        {% endif %}
                    </a>
                    <div class="Card-content">
                        <strong class="Card-title">
                            <a href="{% url 'products:product' action.target_id %}">{{ action.target.title }}</a>
                        </strong>
                        <div class="Card-description">
                            <div class="Card-cost">
                                {% if action.target.get_new_price_and_sale.new_price %}
                                    <span class="Card-priceOld">${{ action.target.get_old_price }}</span>
                                    <span class="Card-price">${{ action.target.get_new_price_and_sale.new_price|default:"NONE" }}</span>
                                {% else %}
                                    <span class="Card-price">${{ action.target.get_old_price }}</span>
                                {% endif %}
                            </div>
                            <div class="Card-category">{{ action.target.category }}
                            </div>
                            <div class="Card-hover">
{#                                <a class="Card-btn" href="#">#}
{#                                    <img src="{% static 'assets/img/icons/card/bookmark.svg' %}" alt="bookmark.svg"/>#}
{#                                </a>#}
                                <a class="Card-btn"
                                   href="{% url 'products:product' action.target_id %}">
                                    <img src="{% static 'assets/img/icons/card/cart.svg' %}" alt="cart.svg"/>
                                </a>
                                <a class="Card-btn" href="{% url 'products:add_to_comparison' pk=action.target_id %}">
                                    <img src="{% static 'assets/img/icons/card/change.svg' %}" alt="change.svg"/>
                                </a>
                            </div>
                        </div>
                    </div>

                    {% if action.target.get_new_price_and_sale.sale %}
                        <div class="Card-sale">
                            {{ action.target.get_new_price_and_sale.sale }}
                        </div>
                    {% else %}
                    {% endif %}
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}